### ISSUE TITLE
Add direct support for PyTorch/TorchScript serialized models  

### ISSUE THREAD

**Issue by suhacker1** [trailofbits/fickling#29]
Right now, [pytorch_poc.py](https://github.com/trailofbits/fickling/blob/master/example/pytorch_poc.py) injects malicious code contained within the pickle files of the PyTorch standard model format. This and the [TorchScript serialization format](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/docs/serialization.md) are ZIP archives with pickle files. It would be great to expand upon those and provide users with easy-to-use functions that can directly manipulate these files since they're relatively common.

**Comment by tehgringe** [comment]
I assume this is why the error is thrown when trying to run this against .pt files 

`Traceback (most recent call last):
  File "/usr/local/bin/fickling", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/fickling/cli.py", line 61, in main
    pickled = pickle.Pickled.load(file)
  File "/usr/local/lib/python3.10/site-packages/fickling/pickle.py", line 372, in load
    for info, arg, pos in genops(pickled):
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickletools.py", line 2291, in _genops
    arg = opcode.arg.reader(data)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickletools.py", line 373, in read_stringnl_noescape
    return read_stringnl(f, stripquotes=False)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickletools.py", line 359, in read_stringnl
    data = codecs.escape_decode(data)[0].decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 63: ordinal not in range(128)`

Not raising it as a bug, have subscribed to this enhancement and will test once it is available. I built a script that grabs all the models from HuggingFace, and want to do some safety checks on the files.

**Comment by moormuddy** [comment]
> I built a script that grabs all the models from HuggingFace, and want to do some safety checks on the files.
I think this is an important thing to do. Especially with the explosion of Stable Diffusion, people are sharing models and just assuming they are safe. When I use fickling to check the .ckpt files, I get the same error that you do.

**Comment by suhacker1** [comment]
This issue is primarily fixed by #62. More work is necessary and will be done to extend this to all of the PyTorch file format versions, but that will be contained in separate issues and PRs.
