### ISSUE TITLE
NotImplementedError: TODO: Add support for Opcode BINFLOAT

### ISSUE THREAD

**Issue by shreyansh26** [trailofbits/fickling#7]
I was trying out something sophisticated with a simple model pre-trained on MNIST. But I git this error.

```
Traceback (most recent call last):
  File ".\pytorch_poc.py", line 147, in <module>
    exfil_model.pickled.insert_python_exec(
  File ".\pytorch_poc.py", line 58, in pickled
    self._pickled = Pickled.load(pickle_file)
  File "C:\Python38\lib\site-packages\fickling\pickle.py", line 343, in load
    opcodes.append(Opcode(info=info, argument=arg, data=data, position=pos))
  File "C:\Python38\lib\site-packages\fickling\pickle.py", line 105, in __new__
    raise NotImplementedError(f"TODO: Add support for Opcode {info.name}")
NotImplementedError: TODO: Add support for Opcode BINFLOAT
```

I guess, the project still needs work to allow to make a full-fledged ML-based attack. 
Any plans for when this will be completed?

**Comment by carsonharmon** [comment]
We're looking into this right now along with some other operations. I'll update this ticket when its complete

**Comment by ESultanik** [comment]
This should work in `master` now and will be included in the next release
